
package ro.pub.cs.aipi.lab06.reservation;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Reservation", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Reservation {


    /**
     * 
     * @return
     *     returns java.util.List<ro.pub.cs.aipi.lab06.reservation.Interval>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeTable", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.GetTimeTable")
    @ResponseWrapper(localName = "getTimeTableResponse", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.GetTimeTableResponse")
    @Action(input = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/getTimeTableRequest", output = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/getTimeTableResponse")
    public List<Interval> getTimeTable();

    /**
     * 
     * @param interval
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableSeats", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.GetAvailableSeats")
    @ResponseWrapper(localName = "getAvailableSeatsResponse", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.GetAvailableSeatsResponse")
    @Action(input = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/getAvailableSeatsRequest", output = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/getAvailableSeatsResponse")
    public int getAvailableSeats(
        @WebParam(name = "interval", targetNamespace = "")
        Interval interval);

    /**
     * 
     * @param customerId
     * @param interval
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.CancelReservationResponse")
    @Action(input = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/cancelReservationRequest", output = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/cancelReservationResponse")
    public boolean cancelReservation(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId,
        @WebParam(name = "interval", targetNamespace = "")
        Interval interval);

    /**
     * 
     * @param customerId
     * @param interval
     * @param noOfSeatsRequired
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.MakeReservationResponse")
    @Action(input = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/makeReservationRequest", output = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/makeReservationResponse")
    public boolean makeReservation(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId,
        @WebParam(name = "interval", targetNamespace = "")
        Interval interval,
        @WebParam(name = "noOfSeatsRequired", targetNamespace = "")
        int noOfSeatsRequired);

    /**
     * 
     * @param customerId
     * @return
     *     returns java.util.List<ro.pub.cs.aipi.lab06.reservation.ReservationData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservations", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.GetReservations")
    @ResponseWrapper(localName = "getReservationsResponse", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", className = "ro.pub.cs.aipi.lab06.reservation.GetReservationsResponse")
    @Action(input = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/getReservationsRequest", output = "http://reservation.lab06.aipi.cs.pub.ro/Reservation/getReservationsResponse")
    public List<ReservationData> getReservations(
        @WebParam(name = "customerId", targetNamespace = "")
        int customerId);

}
