
package ro.pub.cs.aipi.lab06.reservation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Reservation", targetNamespace = "http://reservation.lab06.aipi.cs.pub.ro/", wsdlLocation = "http://localhost:8080/reservation/Reservation?wsdl")
public class Reservation_Service
    extends Service
{

    private final static URL RESERVATION_WSDL_LOCATION;
    private final static WebServiceException RESERVATION_EXCEPTION;
    private final static QName RESERVATION_QNAME = new QName("http://reservation.lab06.aipi.cs.pub.ro/", "Reservation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/reservation/Reservation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATION_WSDL_LOCATION = url;
        RESERVATION_EXCEPTION = e;
    }

    public Reservation_Service() {
        super(__getWsdlLocation(), RESERVATION_QNAME);
    }

    public Reservation_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATION_QNAME, features);
    }

    public Reservation_Service(URL wsdlLocation) {
        super(wsdlLocation, RESERVATION_QNAME);
    }

    public Reservation_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATION_QNAME, features);
    }

    public Reservation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Reservation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationPort")
    public Reservation getReservationPort() {
        return super.getPort(new QName("http://reservation.lab06.aipi.cs.pub.ro/", "ReservationPort"), Reservation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationPort")
    public Reservation getReservationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://reservation.lab06.aipi.cs.pub.ro/", "ReservationPort"), Reservation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATION_EXCEPTION!= null) {
            throw RESERVATION_EXCEPTION;
        }
        return RESERVATION_WSDL_LOCATION;
    }

}
