package ro.pub.cs.aipi.lab05.reservation;

/**
* reservation/MomentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:20:14 AM EET
*/

public final class MomentHolder implements org.omg.CORBA.portable.Streamable
{
  public ro.pub.cs.aipi.lab05.reservation.Moment value = null;

  public MomentHolder ()
  {
  }

  public MomentHolder (ro.pub.cs.aipi.lab05.reservation.Moment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ro.pub.cs.aipi.lab05.reservation.MomentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ro.pub.cs.aipi.lab05.reservation.MomentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ro.pub.cs.aipi.lab05.reservation.MomentHelper.type ();
  }

}
