package ro.pub.cs.aipi.lab05.reservation;


/**
* reservation/UnspecifiedTimeTable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:20:14 AM EET
*/

public final class UnspecifiedTimeTable extends org.omg.CORBA.UserException
{

  public UnspecifiedTimeTable ()
  {
    super(UnspecifiedTimeTableHelper.id());
  } // ctor


  public UnspecifiedTimeTable (String $reason)
  {
    super(UnspecifiedTimeTableHelper.id() + "  " + $reason);
  } // ctor

} // class UnspecifiedTimeTable
