package ro.pub.cs.aipi.lab05.reservation;


/**
* reservation/Date.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:19:56 AM EET
*/

public final class Date implements org.omg.CORBA.portable.IDLEntity
{
  public int day = (int)0;
  public int month = (int)0;
  public int year = (int)0;

  public Date ()
  {
  } // ctor

  public Date (int _day, int _month, int _year)
  {
    day = _day;
    month = _month;
    year = _year;
  } // ctor

} // class Date
