package ro.pub.cs.aipi.lab05.reservation;


/**
* reservation/ReservationServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:19:56 AM EET
*/

abstract public class ReservationServiceHelper
{
  private static String  _id = "IDL:reservation/ReservationService:1.0";

  public static void insert (org.omg.CORBA.Any a, ro.pub.cs.aipi.lab05.reservation.ReservationService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ro.pub.cs.aipi.lab05.reservation.ReservationService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ro.pub.cs.aipi.lab05.reservation.ReservationServiceHelper.id (), "ReservationService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ro.pub.cs.aipi.lab05.reservation.ReservationService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ReservationServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ro.pub.cs.aipi.lab05.reservation.ReservationService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ro.pub.cs.aipi.lab05.reservation.ReservationService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ro.pub.cs.aipi.lab05.reservation.ReservationService)
      return (ro.pub.cs.aipi.lab05.reservation.ReservationService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ro.pub.cs.aipi.lab05.reservation._ReservationServiceStub stub = new ro.pub.cs.aipi.lab05.reservation._ReservationServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ro.pub.cs.aipi.lab05.reservation.ReservationService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ro.pub.cs.aipi.lab05.reservation.ReservationService)
      return (ro.pub.cs.aipi.lab05.reservation.ReservationService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ro.pub.cs.aipi.lab05.reservation._ReservationServiceStub stub = new ro.pub.cs.aipi.lab05.reservation._ReservationServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
