package ro.pub.cs.aipi.lab05.reservation;

/**
* reservation/ReservationServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:19:56 AM EET
*/

public final class ReservationServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ro.pub.cs.aipi.lab05.reservation.ReservationService value = null;

  public ReservationServiceHolder ()
  {
  }

  public ReservationServiceHolder (ro.pub.cs.aipi.lab05.reservation.ReservationService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ro.pub.cs.aipi.lab05.reservation.ReservationServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ro.pub.cs.aipi.lab05.reservation.ReservationServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ro.pub.cs.aipi.lab05.reservation.ReservationServiceHelper.type ();
  }

}
