package ro.pub.cs.aipi.lab05.reservation;


/**
* reservation/ReservationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:19:56 AM EET
*/

public interface ReservationServiceOperations 
{
  ro.pub.cs.aipi.lab05.reservation.Interval[] getTimeTable () throws ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable;
  int getAvailableSeats (ro.pub.cs.aipi.lab05.reservation.Interval interval) throws ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable;
  boolean makeReservation (int customerId, ro.pub.cs.aipi.lab05.reservation.Interval interval, int numberOfSeats) throws ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable;
  boolean cancelReservation (int customerId, ro.pub.cs.aipi.lab05.reservation.Interval interval) throws ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable;
  ro.pub.cs.aipi.lab05.reservation.ReservationInformation[] getReservations (int customerId) throws ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable;
} // interface ReservationServiceOperations
