package ro.pub.cs.aipi.lab05.reservation;

/**
* reservation/UnspecifiedTimeTableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:19:56 AM EET
*/

public final class UnspecifiedTimeTableHolder implements org.omg.CORBA.portable.Streamable
{
  public ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable value = null;

  public UnspecifiedTimeTableHolder ()
  {
  }

  public UnspecifiedTimeTableHolder (ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ro.pub.cs.aipi.lab05.reservation.UnspecifiedTimeTableHelper.type ();
  }

}
