package ro.pub.cs.aipi.lab05.reservation;


/**
* reservation/ReservationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reservation.idl
* Monday, November 10, 2014 3:20:14 AM EET
*/

public interface ReservationService extends ReservationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ReservationService
